name: Android Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JDK_VERSION: 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ env.JDK_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: |
          cp capacitor.config.deploy.ts capacitor.config.ts
          npm install
          npm install ./externals/capacitor-background-mode


      - name: Build Web
        run: npm run build-vite

      - name: Build Capacitor Android Project
        run: npx cap sync android

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Build the Android app
        run: |
          cd android
          ./gradlew bundle && ./gradlew assembleRelease

      - name: Sign dev build
        run: apksigner sign --ks android/release.decrypted.jks --ks-key-alias release --ks-pass env:RELEASE_KEYSTORE_PASSWORD --key-pass env:RELEASE_KEY_ALIAS_PASSWORD --out ./android/app/build/outputs/apk/release/app-release-signed.apk ./android/app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release-signed.apk
